name: build and deploy
on:
 push:
   branches:
     - main

jobs:
 Deploy:
   runs-on: ubuntu-latest
   steps:
     - name: git clone
       uses: actions/checkout@v2

#     - name: npm install
#       run: npm install

#     - name: npm run build
#       run: npm run build

     - name: deploy
       env:
          AWS_ACCESS_KEY_ID: '$'
          AWS_SECRET_ACCESS_KEY: '$'
       run:
          aws s3 cp --recursive --region ap-northeast-2 dist s3://dsk-cicd-bucket